DISPLAY_HEIGHT = 221
DISPLAY_BG_COLOUR = "#F5F5F5"
DISPLAY_LABEL_BG_COLOUR = "#25265E"
DISPLAY_LABEL_FG_COLOUR = DISPLAY_BG_COLOUR
DISPLAY_LABEL_PADX = 24
DISPLAY_TOTAL_LABEL_FONT = ("Inter", 16)
DISPLAY_CURRENT_LABEL_FONT = ("Inter", 40, "bold")